<?php

namespace App\Observers;

use App\Models\MembershipApplication;
use App\Models\Profile;
use App\Models\Role;
use App\Services\NotificationService;
use Illuminate\Support\Facades\DB;

class MembershipApplicationObserver
{
    /**
     * Handle the MembershipApplication "created" event.
     */
    public function created(MembershipApplication $application): void
    {
        // Build notification message with documents info if available
        $uploadedDocuments = [];

        if ($application->id_document_front) {
            $uploadedDocuments[] = 'ID Document (Front)';
        }
        if ($application->id_document_back) {
            $uploadedDocuments[] = 'ID Document (Back)';
        }
        if ($application->proof_of_income) {
            $uploadedDocuments[] = 'Proof of Income';
        }

        $description = "{$application->first_name} {$application->last_name} submitted a membership application.";
        if (! empty($uploadedDocuments)) {
            $description .= ' Submitted with documents: '.implode(', ', $uploadedDocuments);
        }

        app(NotificationService::class)->notifyAdmins(
            'New membership application',
            $description,
            notifiableType: 'membership_application',
            notifiableId: $application->id
        );
    }

    /**
     * Handle the MembershipApplication "updated" event.
     */
    public function updated(MembershipApplication $application): void
    {
        // Check if status changed to 'approved' and profile_id is null
        if ($application->wasChanged('status') && $application->status === 'approved' && ! $application->profile_id) {
            DB::transaction(function () use ($application) {
                // Get Member role
                $memberRole = Role::where('name', 'Member')->firstOrFail();

                // Create profile from application data
                $profile = Profile::create([
                    'first_name' => $application->first_name,
                    'middle_name' => $application->middle_name,
                    'last_name' => $application->last_name,
                    'email' => $application->email,
                    'mobile_number' => $application->mobile_number,
                    'birthdate' => $application->birthdate,
                    'sex' => $application->sex,
                    'address' => $application->address,
                    'roles_id' => $memberRole->id,
                ]);

                // Observer - remove approved_at here, controller already set it
                $application->updateQuietly([
                    'profile_id' => $profile->profile_id,
                    // 'approved_at' => now(),  ← remove this
                ]);

                // Create user account with autogenerated password and send email
                app(NotificationService::class)->createUserWithAutoPassword($profile);

                // Notify applicant and admin team
                app(NotificationService::class)->notifyProfileWithPush(
                    $profile->profile_id,
                    'Membership application approved',
                    'Your membership application has been approved and an account has been created.',
                    notifiableType: 'membership_application',
                    notifiableId: $application->id
                );

                app(NotificationService::class)->notifyAdmins(
                    'Membership application approved',
                    "{$profile->full_name} (Profile ID: {$profile->profile_id}) approved.",
                    notifiableType: 'membership_application',
                    notifiableId: $application->id
                );
            });
        }

        // Check if documents were added/updated
        $documentFields = ['id_document_front', 'id_document_back', 'proof_of_income', 'other_documents'];
        $uploadedDocuments = [];

        foreach ($documentFields as $field) {
            if ($application->wasChanged($field) && $application->{$field}) {
                $uploadedDocuments[] = str_replace('_', ' ', ucwords($field));
            }
        }

        if (! empty($uploadedDocuments) && $application->profile_id) {
            // Notify member of document registration
            app(NotificationService::class)->notifyDocumentUpload(
                $application->profile_id,
                implode(', ', $uploadedDocuments),
                notifiableType: 'membership_application',
                notifiableId: $application->id
            );

            // Notify admins
            app(NotificationService::class)->notifyAdmins(
                'Membership Application Documents Updated',
                "Documents updated for {$application->first_name} {$application->last_name}: ".implode(', ', $uploadedDocuments),
                notifiableType: 'membership_application',
                notifiableId: $application->id
            );
        }
    }
}
