<x-filament-panels::page>
    @include('filament.reports.partials.styles')

    @php($report = $this->reportData())

    <div class="report-shell space-y-6">
        <div class="rounded-3xl border border-slate-200 bg-white px-6 py-6 shadow-sm dark:border-slate-800 dark:bg-slate-950">
            <div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                <div class="space-y-2">
                    <div class="inline-flex rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1 text-[0.68rem] font-semibold uppercase tracking-[0.22em] text-emerald-700 dark:text-emerald-300">
                        {{ $report['coop_name'] }}
                    </div>

                    <div>
                        <h1 class="text-2xl font-bold tracking-tight text-slate-900 dark:text-white">
                            {{ $report['title'] }}
                        </h1>
                        <p class="mt-1 max-w-3xl text-sm text-slate-500 dark:text-slate-400">
                            {{ $report['subtitle'] }}
                        </p>
                    </div>
                </div>

                <div class="grid gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700 shadow-sm dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300 lg:min-w-[300px]">
                    <div class="flex items-center justify-between gap-6">
                        <span class="text-slate-500 dark:text-slate-400">Date Generated</span>
                        <span class="font-medium text-slate-900 dark:text-white">{{ $report['generated_at']->format('M d, Y h:i A') }}</span>
                    </div>
                    <div class="flex items-center justify-between gap-6">
                        <span class="text-slate-500 dark:text-slate-400">Generated By</span>
                        <span class="font-medium text-slate-900 dark:text-white">{{ $report['generated_by'] }}</span>
                    </div>
                    <div class="flex items-center justify-between gap-6">
                        <span class="text-slate-500 dark:text-slate-400">Period</span>
                        <span class="font-medium text-slate-900 dark:text-white">{{ $report['filters']['start'] }} - {{ $report['filters']['end'] }}</span>
                    </div>
                    @if ($report['filters']['branch'])
                        <div class="flex items-center justify-between gap-6">
                            <span class="text-slate-500 dark:text-slate-400">Branch</span>
                            <span class="font-medium text-slate-900 dark:text-white">{{ $report['filters']['branch'] }}</span>
                        </div>
                    @endif
                    @if ($report['filters']['member'])
                        <div class="flex items-center justify-between gap-6">
                            <span class="text-slate-500 dark:text-slate-400">Member</span>
                            <span class="font-medium text-slate-900 dark:text-white">{{ $report['filters']['member'] }}</span>
                        </div>
                    @endif
                </div>
            </div>
        </div>

        <div class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
            {{ $this->form }}
        </div>

        @include('filament.reports.partials.panel', ['report' => $report])
    </div>

    <x-filament-actions::modals />
</x-filament-panels::page>