<div class="header">
    <p class="title">{{ $report['coop_name'] }}</p>
    @if (!empty($report['coop_address']))
        <p class="subtitle">{{ $report['coop_address'] }}</p>
    @endif
    <div class="meta-grid">
        <div class="meta-cell">
            <div class="meta-box">
                <div class="meta-row">
                    <span class="label">Report Title</span>
                    <span class="value">{{ $report['title'] }}</span>
                </div>
                <div class="meta-row">
                    <span class="label">Date Generated</span>
                    <span class="value">{{ $report['generated_at']->format('M d, Y h:i A') }}</span>
                </div>
                <div class="meta-row">
                    <span class="label">Generated By</span>
                    <span class="value">{{ $report['generated_by'] }}</span>
                </div>
            </div>
        </div>
        <div class="meta-cell">
            <div class="meta-box">
                <div class="meta-row">
                    <span class="label">Date Range</span>
                    <span class="value">{{ $report['filters']['start'] }} - {{ $report['filters']['end'] }}</span>
                </div>
                @if (!empty($report['filters']['branch']))
                    <div class="meta-row">
                        <span class="label">Branch</span>
                        <span class="value">{{ $report['filters']['branch'] }}</span>
                    </div>
                @endif
                @if (!empty($report['filters']['member']))
                    <div class="meta-row">
                        <span class="label">Member</span>
                        <span class="value">{{ $report['filters']['member'] }}</span>
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>